### ISSUE TITLE
NullPointException

### ISSUE THREAD

**Issue by xiejinhong** [0xlau/LiteFlowX#5]
Idea版本：2023.2.5

![image](https://github.com/0xlau/LiteFlowX/assets/13741156/b96e372e-4cf4-4941-94c9-5792289ce98a)

java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because the return value of "com.intellij.psi.PsiClass.getQualifiedName()" is null
	at top.xystudio.plugin.idea.liteflowx.service.LiteFlowService._isLiteFlow(LiteFlowService.java:206)
	at top.xystudio.plugin.idea.liteflowx.service.LiteFlowService.isLiteFlowIfComponent(LiteFlowService.java:280)
	at top.xystudio.plugin.idea.liteflowx.system.provider.FileIconProvider.getLiteFlowFileIcon(FileIconProvider.java:37)
	at top.xystudio.plugin.idea.liteflowx.system.provider.FileIconProvider.getIcon(FileIconProvider.java:26)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:98)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:94)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:94)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:45)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.kt:72)
	at com.intellij.ui.icons.CoreIconManager.createDeferredIcon(CoreIconManager.kt:117)
	at com.intellij.psi.impl.ElementBase.computeIcon(ElementBase.java:85)
	at com.intellij.psi.impl.ElementBase.getIcon(ElementBase.java:62)
	at com.intellij.ide.navbar.impl.PsiNavBarItem.getIcon(DefaultNavBarItem.kt:150)
	at com.intellij.ide.navbar.impl.DefaultNavBarItem.presentation(DefaultNavBarItem.kt:53)
	at com.intellij.ide.navbar.ide.NavBarVmItemKt.toVmItems(NavBarVmItem.kt:50)
	at com.intellij.ide.navbar.ide.NavBarServiceKt.contextModelInner(NavBarService.kt:159)
	at com.intellij.ide.navbar.ide.NavBarServiceKt.access$contextModelInner(NavBarService.kt:1)
	at com.intellij.ide.navbar.ide.NavBarServiceKt$contextModel$2.invoke(NavBarService.kt:137)
	at com.intellij.ide.navbar.ide.NavBarServiceKt$contextModel$2.invoke(NavBarService.kt:136)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:105)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:41)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:39)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:37)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:34)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:76)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:63)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:42)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by gengxiangyu** [comment]
@0xlau 这个空指针的问题什么时候解决下
